apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-monitor
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: simple-monitor
  template:
    metadata:
      labels:
        app: simple-monitor
    spec:
      containers:
      - name: simple-monitor
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
