apiVersion: v1
kind: Service
metadata:
  name: simple-monitor
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: simple-monitor
